// import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="assets/css/global.css" />
        <link rel="stylesheet" href="assets/css/output.css" />
        <script async src="https://cdn.tailwindcss.com"></script>
        {/* <script
          async
          src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp,container-queries"
        ></script> */}
      </head>
      <body className={inter.className}>
        {children}
        <script src="assets/js/main.js" defer async />
      </body>
    </html>
  );
}
